services:
  postgres:
    build: db
    environment:
      POSTGRES_DB: geocoder
      POSTGRES_USER: geocoder
      POSTGRES_PASSWORD: geocoder
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    ports:
     - "1434:11434"
    volumes:
     - ollama:/root/.ollama
volumes:
  postgres:
  ollama:
